# frozen_string_literal: true

require 'codebot/payload'

module Codebot
  # An IRC message generated by a {Request} and sent to a {Channel}.
  class Message
    # @return [Channel] the channel to send this message to
    attr_reader :channel

    # @return [Payload] the parsed request payload
    attr_reader :payload

    # Constructs a new message for delivery to an IRC channel.
    #
    # @param channel [Channel] the channel to send this message to
    # @param payload [Payload] the parsed request payload
    def initialize(channel, payload)
      @channel = channel
      @payload = payload
    end
  end
end
